### PR TITLE
Remove NET45/NET46 in favor of NET462 #1779

### PR DESCRIPTION
**Pull request by bjornbouetsmith**
Removed NET45/46 in favor of NET462 and cleaned up code no longer required

### CODE REVIEW

**Comment by mhowlett** [comment]
lgtm. there's some testing I want to do before merging as it's potentially impactful. i don't see any problem though. 

thanks!

(targeting v1.9.0)

**Comment by mhowlett** [comment]
oh, can you sign the CLA? thanks.

**Comment by mhowlett** [comment]
(i'll merge after that)

**Comment by bjornbouetsmith** [comment]
> oh, can you sign the CLA? thanks.

I have, but but somehow your BOT is not working.

image

**Pull request merged**
