### PR TITLE
Multi-shema avro deserializer.

### PR DESCRIPTION
**Pull request by ycherkes**
Add an ability to consume/produce messages of multiple types on a single topic.

### CODE REVIEW

**Comment by mhowlett** [comment]
Hi @ycherkes, @smurtdev - thanks for your efforts here, this is looking good (nice and clean).

The plan I had in the back of my mind to tackle this use case was more ambitious (unlikely to be done in the near term), and tied in with other goals. I'm thinking we should have a dispatching consumer that can divert messages based on type.

Because of that, my thinking at the moment is that i'll be recommending this code be put in a separate package not maintained by us. But you've also sparked of a discussion about us possibly advertising such packages from the README.md to make them easily discoverable. For the moment, feel free to keep adding code here.

**Comment by ycherkes** [comment]
> But you've also sparked of a discussion about us possibly advertising such packages from the README.md to make them easily discoverable.

Hi @mhowlett . I've created a separate repository [multi-schema-avro-desrializer](https://github.com/ycherkes/multi-schema-avro-desrializer) and put a package to NuGet [YCherkes.SchemaRegistry.Serdes.Avro](https://www.nuget.org/packages/YCherkes.SchemaRegistry.Serdes.Avro).

**Comment by mhowlett** [comment]
Awesome, thanks. I've started making a PR to document a list of 3rd party libraries, and have added this one. It's not open yet, should be soon.

**Comment by ycherkes** [comment]
> Awesome, thanks. I've started making a PR to document a list of 3rd party libraries, and have added this one. It's not open yet, should be soon.

Great news, thanks.

**Comment by mhowlett** [comment]
FYI: https://github.com/confluentinc/confluent-kafka-dotnet/pull/1696/files

Did intend to put more effort into curating the list, but this will do as a start.

**Comment by mhowlett** [comment]
closing this, having opened the 3rd party page PR.

**Comment by ycherkes** [comment]
> FYI: https://github.com/confluentinc/confluent-kafka-dotnet/pull/1696/files
> 
> Did intend to put more effort into curating the list, but this will do as a start.

Got it. Thank you.

**Pull request closed without merging**
