### PR TITLE
Correct task awaiting with ConfigureAwait(false) in Producer.

### PR DESCRIPTION
**Pull request by levdimov**
This fix resolves an issue when client code waits ProduceAsync synchronously (using `.Result` or `.GetAwaiter().GetResult()`). This fix is very useful for keeping backward compatability with legacy code which you cannot easily migrate to async. As I wrote [here](https://github.com/confluentinc/confluent-kafka-dotnet/issues/939#issuecomment-497264799) before 1.0.0 Producer code was returning tasks rather than awaiting them inside implementation.

I also added ConfigureAwaitChecker.Analyzer package so you will have warnings in future

### CODE REVIEW

**Comment by levdimov** [comment]
[clabot:check]

**Comment by mhowlett** [comment]
looks good except for unnecessary white space changes (these make it difficult to track what changes happened when). also, I'm not keen on the `ConfigureAwaitChecker.Analyzer` dependency. I don't know why it would be a problem, but as a rule of thumb, prefer to not to have dependencies unless critical. if you make those changes, LGTM. Thanks!

**Comment by levdimov** [comment]
Sorry about whitespace changes, my IDE is removing trailing whitespaces automatically and I hide all whitespace changes in Git UI :)

Also I've removed `ConfigureAwaitChecker.Analyzer`. Personally, I don't see any problems with private dependencies, but you are the boss :)

Thank you!

**Comment by mhowlett** [comment]
thanks! I also don't see any problem, but I don't have time to give it any thought and not including it is definitely 100% safe.

**Comment by levdimov** [comment]
@mhowlett, may I ask you when these changes are going to be released?

**Comment by mhowlett** [comment]
I've opened #968 so we can release asap - so hopefully soon, but there is some internal debate as to how to best do rapid releases moving forward. this is a test case for that.

**Pull request merged**
