### PR TITLE
rework Config ctors v2

### PR DESCRIPTION
**Pull request by AndyPook**
* delegate to base ctors
 * simplify the creation of the kvp -> dictionary
 * add ability to update a dictionary "in place"
Last one is handy for config validation, setting defaults etc in dotnetCore IOptions stuff

this is a replacement for #881 in that it _just_ reworks to ctors but does not add the KeyNames generation parts. Follow the conversation in that pr up to around May 2 for relevant comment

### CODE REVIEW

**Comment by mhowlett** [comment]
sorry for the delay, EoQ priorities...

**Comment by mhowlett** [comment]
just got back to this.

this PR now has a dependency on https://github.com/edenhill/librdkafka/pull/2416 since generation of configs is currently broken.

also, I see the PR is mostly white space. you can fix that and we can iterate, or i'll just pull out the changes and do a PR myself (probably easier). the only downside is you don't get your name on the merge.

**Comment by AndyPook** [comment]
fixed up the WS. At least, made it consistent. There was previously a mix of space (or not) at the line ending. I've killed them all.

I think it's fairly clear what's going on the the `Config_gen.cs` file now?

**Comment by AndyPook** [comment]
@mhowlett WRT edenhill/librdkafka#2416 ...

Instead of changing the upstream, I've replaced the `Split` with something a little smarter.
This only "splits" on ` | ` and so should not get confused by the `||` in the config markup

**Comment by AndyPook** [comment]
ping?

**Comment by mhowlett** [comment]
lgtm, thanks! made it into 1.2 :-).

**Pull request merged**
