### PR TITLE
Fix exception

### PR DESCRIPTION
**Pull request by xqrzd**
Small typo

### CODE REVIEW

**Comment by mhowlett** [comment]
nice catch! can i trouble you to reopen onto 1.0.x? I'll merge once 1.0 is out and include it in 1.0.1. (at the current time, it's strictly breaking changes only being merged).

**Comment by xqrzd** [comment]
Done. I used merge instead of rebase / force push, is it easy for you to squash the commits, or should I handle that?

**Comment by mhowlett** [comment]
can't easily merge this. `cherry-pick` probably easiest. i can fix this myself no-problem-at-all, but was preferring to merge pr with your name on it to give you the credit...

**Comment by xqrzd** [comment]
Sounds good

**Pull request closed without merging**
