### PR TITLE
Extensible avro serializer/deserializer 

### PR DESCRIPTION
**Pull request by imhotepper**
Updated the SerializeAsync and DeserializeAsync for the Avro serializer/deserializer so that they are extensible. As a use case, now it is possible to add encryption/decryption to the messages sent to and from the topics.

### CODE REVIEW

**Comment by imhotepper** [comment]
[clabot:check]

**Comment by mhowlett** [comment]
can you use composition for this instead?

**Comment by imhotepper** [comment]
indeed I can use composition. thanks for the feed back. I will close the pull request.

**Comment by mhowlett** [comment]
cool. i think composition here is better, so i think better to have an API which pushes people towards that.

**Pull request closed without merging**
