### PR TITLE
Update NJsonSchema to v11

### PR DESCRIPTION
**Pull request by NoahStolk**
(Original PR: https://github.com/confluentinc/confluent-kafka-dotnet/pull/2185)

Fixes https://github.com/confluentinc/confluent-kafka-dotnet/issues/2169

A few notes:
- This is a breaking change, and should be included in a major version release only, as we're dropping support for NJsonSchema v10. This change **will** impact users that manage their own references to NJsonSchema v10.
- Newtonsoft.Json-based generators have been moved to a separate NuGet package, so the reference to NJsonSchema has been replaced with a reference to NJsonSchema.NewtonsoftJson. See [NSwag 14 announcement](https://github.com/RicoSuter/NSwag/issues/4524) and [NJsonSchema v11 release notes](https://github.com/RicoSuter/NJsonSchema/releases/tag/v11.0.0).
- `EnumHandling` no longer exists, so the `WithJsonSchemaGeneratorSettingsSerDe` unit test has been updated to use `JsonSerializerSettings` instead.

### CODE REVIEW

**Review by rayokota — APPROVED** [review]
Thanks @NoahStolk , LGTM

**Comment by rayokota** [comment]
@NoahStolk , I intend to merge this PR, and then we can figure out a subsequent PR to figure out how best to minimize breaking backward compatibility.  Unfortunately I can't merge at the moment as we're doing some internal work to change the protection rules for public repos.

**Comment by rayokota** [comment]
@NoahStolk , just an FYI that we don't have an ETA for when the protection rules will be fixed (hopefully in a few weeks), but I won't forget about this PR.

**Comment by NoahStolk** [comment]
Thanks @rayokota, do you plan to merge this PR as is, and then add the `NET8_0_OR_GREATER` directives? Or should they be included in this branch before the merge?

**Comment by rayokota** [comment]
If you want to add it to this PR, that would be great.  Otherwise we could add it to a subsequent PR

**Comment by rayokota** [comment]
@NoahStolk , on second thought, can you take a look at adding the directives to this PR?  So that we don't break users in case we need to cut a patch release from master.  Thanks!

**Comment by NoahStolk** [comment]
Will try to find some time to do that this week.

**Review by rayokota — APPROVED** [review]
Thanks @NoahStolk , LGTM

**Comment by NoahStolk** [comment]
Thanks @rayokota 

FYI: Not all (.NET 8) unit tests are passing yet, I'm getting some of these errors.

image

Any ideas? If not I'll debug some time later. Haven't had a lot of time to look into this yet.

I also don't have .NET 6 installed anymore, so I don't know if the old tests are still passing.

I had another question... Do we need to multi-target the `JsonWithReferences` and `Confluent.SchemaRegistry.Serdes.IntegrationTests` projects? I just upgraded them to .NET 8.

**Comment by rayokota** [comment]
Thanks @NoahStolk , I believe the .NET 6 tests are still passing.  Yeah, I'm not sure about the .NET 8 ones.  Let me know if you can't figure it out and maybe I can take a look as well.

**Comment by rayokota** [comment]
Thanks @NoahStolk.  The issue is https://github.com/RicoSuter/NJsonSchema/issues/1696.  I'll merge this PR and fix the tests in a subsequent PR.

**Comment by NoahStolk** [comment]
Thank you!

**Pull request merged**
