### PR TITLE
netcoreapp1.0 -> netstandard1.3

### PR DESCRIPTION
**Pull request by mhowlett**
this was errantly included in PR #38

### CODE REVIEW

**Comment by mhowlett** [comment]
@edenhill

**Comment by edenhill** [comment]
This only changes the main module, shouldnt all places be changed?
```
$ git grep netcoreapp
Makefile:LINUX_FRAMEWORK=netcoreapp1.0
examples/AdvancedConsumer/project.json:        "netcoreapp1.0": {
examples/AdvancedProducer/project.json:        "netcoreapp1.0": {
examples/FSharp/project.json:    "netcoreapp1.1": {
examples/Misc/project.json:        "netcoreapp1.0": {
examples/MultiProducer/project.json:        "netcoreapp1.0": {
examples/SimpleConsumer/project.json:        "netcoreapp1.0": {
examples/SimpleProducer/project.json:        "netcoreapp1.0": {
src/Confluent.Kafka/project.json:        "netcoreapp1.0": {
test/Confluent.Kafka.Benchmark/project.json:    "netcoreapp1.0": {
test/Confluent.Kafka.IntegrationTests/project.json:    "netcoreapp1.0": {
test/Confluent.Kafka.UnitTests/project.json:        "netcoreapp1.0": {
test/Confluent.Kafka.VerifiableClient/project.json:        "netcoreapp1.0": {
```

**Comment by mhowlett** [comment]
netstandard is only for libraries.

from https://blogs.msdn.microsoft.com/cesardelatorre/2016/06/28/running-net-core-apps-on-multiple-frameworks-and-what-the-target-framework-monikers-tfms-are-about/

> As simple rules to follow:
>
> App Developers: You target the platform TFM you’re writing for ( netcoreapp1.0, uap10.0 ,  net452 ,  xamarinios , etc.).
> 
> Package/Library Authors: Target the lowest  netstandard  version you can. You will run on all platforms that support that  netstandard  version or higher

**Comment by edenhill** [comment]
okay, LGTM

**Pull request merged**
