### PR TITLE
WIP: Fix Accessviolation when handler creation fails

### LINKED ISSUE #125: AccessViolationException with SSL configuration (consumer)
I'm running Confluent.Kafka client (0.9.4) with .Net framework 4.5.1. While it works fine without SSL, consumer client throws **AccessViolationException** with SSL configuration: 

```
{
            {"group.id", kafkaGroup}, 
            {"client.id", clientId}, 
            {"bootstrap.servers", kafkaServer}, 
            {"enable.auto.commit", true},
            {"security.protocol", "ssl" },
            {"ssl.key.location", "sslkey/client.keystore.jks"},
            { "ssl.key.password", "testtest" },
            { "auto.commit.interval.ms", 5000},
            { "default.topic.config", new Dictionary<string, object>()
                {
                    { "auto.offset.reset", "smallest" }
                }
            }

        }
```

### PR DESCRIPTION
**Pull request by treziac**
Fix #125 
Not sure how to test given ssl configuration, but I can with providing a null socket_cb for example to test when rd_kafka_create fail.

### CODE REVIEW

**Comment by edenhill** [comment]
The caller should actually free the conf_t if rd_kafka_new() fails.
This has been a bit buggy in previous releases of librdkafka but 0.11.0 should get it right.

**Comment by treziac** [comment]
Thanks! still a bug to fix in this case (replace skh/GetDangerousHandle by config, it's config which should be closed
I couldn't reprouce as rd_kafka_new always succeed, will complete it tomorrow

**Comment by mhowlett** [comment]
Thanks @treziac - good catch. Will merge after you make that change.

**Comment by edenhill** [comment]
@treziac You can probably specify an invalid `ssl.ca.location` or so.

**Comment by treziac** [comment]
(tested on both 0.9.5 and 0.11.0 RC)

**Comment by mhowlett** [comment]
☀️🍉LGTM

**Pull request merged**
