### PR TITLE
Fix mistaken assert in PartitionEOF.

### PR DESCRIPTION
**Pull request by Mousavi310**
It seems that we must assert cr2 instead of cr1. We already asserted cr1.

### CODE REVIEW

**Comment by mhowlett** [comment]
you are indeed correct. can you sign the CLA and retarget to the 1.0.x branch? thanks!

**Comment by Mousavi310** [comment]
Sure, I will sign it and resend my pull request.

**Comment by Mousavi310** [comment]
[clabot:check]

**Comment by mhowlett** [comment]
merge #852 instead

**Pull request closed without merging**
