### PR TITLE
Target netstandard

### PR DESCRIPTION
**Pull request by treziac**
A library should target netstandard, not netcoreapp
Also updated dependencies version

### CODE REVIEW

**Comment by mhowlett** [comment]
thanks @treziac 
hmm. I actually caught the netstandard -> netcoreapp issue before, I'll investigate how it managed to get through.

**Comment by treziac** [comment]
Seems to be in Kafkatest client [WIP]
Also I didn't push it, but a sdk property in global.json needs to be adde when any sdk msbuild (preview3+) is installed. I assume project will migrate to csproj when release come in march

**Comment by mhowlett** [comment]
FYI: I'm going to open a new PR on 0.9.4.x with only the netcoreapp -> netstandard one line change and leave this PR open on master.

An thanks for your additional notes. We're waiting for MS on the build stuff before putting effort into fixing all this up. Also note we haven't been developing under Windows (just building and testing the nuget package).

**Comment by treziac** [comment]
fixed in #57, will eventually create a new one for sln/csproj when vs2017 is out

**Pull request closed without merging**
