### PR TITLE
.NET 8 added as a target to all projects and tests

### PR DESCRIPTION
**Pull request by emasab**
except examples that are built with the older supported version. Semaphore is using latest version to test.
netstandard and netcore targets are removed.

### CODE REVIEW

**Review by rayokota — APPROVED** [review]
Thanks @emasab , LGTM

**Comment by g7ed6e** [comment]
This will break compatibility with .NET Framework users.

**Comment by g7ed6e** [comment]
@rayokota .NET Framework 4.6.2 is supported until 2027 and there is no end of support date for 4.7+ yet and a lot of companies are still running applications on .NET Framework.

**Review by rayokota — APPROVED** [review]
Thanks @emasab , LGTM

**Review by rayokota — APPROVED** [review]
LGTM

**Review by rayokota — APPROVED** [review]
Thanks @emasab , LGTM

**Pull request merged**
