### PR TITLE
Fixed args length check

### PR DESCRIPTION
**Pull request by MrGlenThomas**
Hello, I am a developer at Sunrise Brokers and am looking to make heavy use of Kafka using .NET clients. I would like to contribute to this project and this is a simple first-time commit as I am new to contributing on github. If I am doing this wrong please let me know. Thanks.

The change fixes an index out of bounds exception when no arguments are supplied, due to the validation check being in the wrong place.

### CODE REVIEW

**Comment by edenhill** [comment]
LGTM, just need the CLA signed

**Comment by MrGlenThomas** [comment]
@edenhill I have just signed the agreement and it said "Thanks for your submission", should it update on this page?

**Comment by MrGlenThomas** [comment]
Ah I've got it... [clabot:check]

**Comment by edenhill** [comment]
Thank you for your contribution!

**Pull request merged**
