### PR TITLE
Confluent.Kafka.StrongName project and build

### PR DESCRIPTION
**Pull request by zikifer**
For issue #168 

Created a new project, Confluent.Kafka.StrongName.csproj, that builds using the same source files as Confluent.Kafka.csproj and includes the tags to sign the assembly.  Confluent.Kafka.snk created locally using `sn.exe`.  

Special note:  I was unable to find a way for one project to inherit, or import properties, from another.  So going forward the new Confluent.Kafka.StrongName.csproj file will need to be updated whenever the assembly version number needs to be bumped.

Final output of build from AppVeyor:
```
Total tests: 84. Passed: 84. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 3.1082 Seconds

Collecting artifacts...
Found artifact 'src\Confluent.Kafka\bin\Release\Confluent.Kafka.0.9.5-ci-4.nupkg' matching 'src\**\bin\Release\*.nupkg' path
Found artifact 'src\Confluent.Kafka.StrongName\bin\Release\Confluent.Kafka.StrongName.0.9.5-ci-4.nupkg' matching 'src\**\bin\Release\*.nupkg' path
Uploading artifacts...
[1/2] src\Confluent.Kafka\bin\Release\Confluent.Kafka.0.9.5-ci-4.nupkg (105,079 bytes)...100%
[2/2] src\Confluent.Kafka.StrongName\bin\Release\Confluent.Kafka.StrongName.0.9.5-ci-4.nupkg (106,009 bytes)...100%
Build success
```

### CODE REVIEW

**Comment by zikifer** [comment]
[clabot:check]

**Comment by treziac** [comment]
It's possible to do

`dotnet pack -c %CONFIGURATION% /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=Confluent.Kafka.snk /p:PackageId=Confluent.Kafka.StrongName`

Which seems cleaner to me

**Comment by zikifer** [comment]
I've updated the appveyor build script with suggestions by @treziac and removed the additional project - everything looks good.  Next I will add a new test project that signs itself, and verify it can successfully load the signed Confluent.Kafka assembly.

**Comment by zikifer** [comment]
The Travis-CI build for OSX failed due to "Too many open files".  Looking through the history this has happened a few times in the past.  Is it something I did?

**Comment by treziac** [comment]
Yeah, that's "normal". Will be fixed with #186

Did not test your last addition yet but at first read seems good - just not sure about the way the package is tested with the new csproj which runs the unit tests, but can't find a nice way to do it (on one side I don't like having a csproj which is not referenced in sln, on the other I don't want it to be included in the sln)

I was more thinking on directly referencing the nupkg by adding the artifact folder as a nuget source (so we don't have the reference to the dll&co), but your way may be better - will let @mhowlett to his judgement

Also we need to add nuget metadata to explain what the package is. But as there is no Description attribute in Confluent.Kafka yet, this should be included in a different PR

**Comment by zikifer** [comment]
Agreed, I was not crazy about having a stand-alone project that's outside of the solution to test the signed assembly, but since the signed assembly is not its own project (but rather build parameters) I couldn't come up with a better way.  If you guys have something you'd prefer I'll happily change it.

**Comment by mhowlett** [comment]
well, this PR has also been a good catalyst for fixing the OSX build and adding project meta information :-).

thanks @treziac for driving this. I like your idea of adding a nuget source better, but I also don't think it's worth changing. 

It's a pity we need this extra project file (I also cannot think of away around it). The one thing I think should be done before merging is to add a README to test/Confluent.Kafka.StrongName.UnitTests/ to explain what's going on. In particular note that the project is used by travis build script, which also builds the Confluent.Kafka.StrongName .dll dependency. 

I just did a separate PR that adds metadata to all the project files. We can merge that after this PR and I'll add metadata for this project as well.

**Comment by mhowlett** [comment]
and of course thanks @zikifer for the contributions!

**Comment by mhowlett** [comment]
awesome!

**Comment by zikifer** [comment]
Readme.md has been added.  Let me know if there is anything you'd like me to add.  Thanks!

**Comment by mhowlett** [comment]
artifacts are here: https://ci.appveyor.com/project/edenhill/confluent-kafka-dotnet/build/artifacts

**Comment by zikifer** [comment]
Excellent, thank you @mhowlett !

**Comment by combrinckd** [comment]
How do I get hold of the strong name version of the lib. When adding the normal nuget package I still get the error that it is not strongly named. Please help :(

**Comment by mhowlett** [comment]
For now take the strong name package from appveyor (link below) and put in a local nuget repository (which is easy to create, see for example https://codurance.com/2015/05/04/creating-a-local-nuget-repository/ )

https://ci.appveyor.com/project/mhowlett/confluent-kafka-dotnet-4n9q1/build/1.0.43/artifacts

**Comment by mhowlett** [comment]
ok, I just put a pre-release version on nuget - note that it's pre-release so you'll need to check the relevant box in order to find it in VS.

https://www.nuget.org/packages/Confluent.Kafka.StrongName/0.9.5-ci-43

**Comment by combrinckd** [comment]
Much appreciated!! Will check it out when back at the office. Thanks

**Comment by yaakov-h** [comment]
@mhowlett when does "for now" end? Is a non-pre-release version going to be published to NuGet, and is this going to happen in sync with the non-strong-named version going forwards?

**Comment by treziac** [comment]
@yaakov-h 
The "for now" was before the package was pushed on nuget.
Strong-named package will be pushed at same time than normal package. Only Confluent.Kafka 0.11.0-RC1 has been pushed since strong name was made available (the corresponding StrongName package is available) - you will have to wait 0.11.0 to be available, which should come shortly (librdkafka is in RC2, Confluent.Kafka will follow)

In the meantime, feel free to test the RC and make any commentary. Note that you may also have to target librdkafka.redist 0.11.0-RC2 if you use sasl

**Pull request merged**
